# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import functions_pb2 as functions__pb2


class FederatedAppStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateData = channel.unary_unary(
        '/FederatedApp/GenerateData',
        request_serializer=functions__pb2.Empty.SerializeToString,
        response_deserializer=functions__pb2.Empty.FromString,
        )
    self.Train = channel.unary_unary(
        '/FederatedApp/Train',
        request_serializer=functions__pb2.Empty.SerializeToString,
        response_deserializer=functions__pb2.Model.FromString,
        )
    self.SendModel = channel.unary_unary(
        '/FederatedApp/SendModel',
        request_serializer=functions__pb2.Model.SerializeToString,
        response_deserializer=functions__pb2.Empty.FromString,
        )


class FederatedAppServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenerateData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Train(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FederatedAppServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateData': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateData,
          request_deserializer=functions__pb2.Empty.FromString,
          response_serializer=functions__pb2.Empty.SerializeToString,
      ),
      'Train': grpc.unary_unary_rpc_method_handler(
          servicer.Train,
          request_deserializer=functions__pb2.Empty.FromString,
          response_serializer=functions__pb2.Model.SerializeToString,
      ),
      'SendModel': grpc.unary_unary_rpc_method_handler(
          servicer.SendModel,
          request_deserializer=functions__pb2.Model.FromString,
          response_serializer=functions__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FederatedApp', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
